/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gyjian_algorithm_jni_NativeLib */

#ifndef _Included_com_gyjian_algorithm_jni_NativeLib
#define _Included_com_gyjian_algorithm_jni_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gyjian_algorithm_jni_NativeLib
 * Method:    getAuthCode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gyjian_algorithm_jni_NativeLib_getAuthCode
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint, jint, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
